name: CI / Microservice B
on:
  pull_request_target:
    branches:
      - main
    paths:
      - "microservices/b/**"
  push:
    branches:
      - main
    paths:
      - "microservices/b/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice B > Build"

  test:
    name: Test 
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice B > Test"

  scan:
    name: Scan
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice B > Scan"
