name: CI / Microservice C
on:
  pull_request_target:
    branches:
      - main
    paths:
      - "microservices/c/**"
  push:
    branches:
      - main
    paths:
      - "microservices/c/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice C > Build"

  test:
    name: Test 
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice C > Test"

  scan:
    name: Scan
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice C > Scan"
