name: CI / Microservice D
on:
  pull_request:
    branches:
      - main
    paths:
      - "microservices/d/**"
  push:
    branches:
      - main
    paths:
      - "microservices/d/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice D > Build"

  test:
    name: Test 
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice D > Test"

  scan:
    name: Scan
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Microservice D > Scan"
