name: CI / Default
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "microservices/a/**"
      - "microservices/b/**"
      - "microservices/c/**"
      - "microservices/d/**"
  push:
    branches:
      - main
    paths-ignore:
      - "microservices/a/**"
      - "microservices/b/**"
      - "microservices/c/**"
      - "microservices/d/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Default > Build"

  test:
    name: Test 
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Default > Test"

  scan:
    name: Scan
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Default > Scan"
